import { Navbar } from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IHenriquez - Web Scraping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={(inter.className, "bg-indigo-950 text-tema_letra")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
